name: actionlint
on: 
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1